name: CMake

on: [push, workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  # This will install all the required dependencies to build NESEmu
  install:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y libopengl-dev
    
  # Build the project using cmake
  build:
    needs: install
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Configure CMake in a 'build' subdirectory
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build

      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
